### ISSUE TITLE
跟 Stormpot 比性能怎么样？

### ISSUE THREAD

**Issue by hank-whu** [nextopcn/lite-pool#2]
https://github.com/chrisvest/stormpot

**Comment by leonchen83** [comment]
@hank-whu 
初步测试了下，Stormpot比lite-pool要快，但是lite-pool提供更多的配置项以及更多的可扩展性，如果速度快是必要选项的话，推荐你选择Stormpot。

**Comment by hank-whu** [comment]
@leonchen83 
Stormpot作者不维护了，存在偶尔死锁的问题。
你这个项目准备长期维护吗？

**Comment by leonchen83** [comment]
@hank-whu 
是的，长期维护
就像我们的另一个项目[redis-replicator](https://github.com/leonchen83/redis-replicator)一样，已经发布了30多个release，维护两年。
